/*
 * VSCU - Collection
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"BranchesSelectBranchesPost",
		strings.ToUpper("Post"),
		"/branches/selectBranches",
		BranchesSelectBranchesPost,
	},

	Route{
		"CodeSelectCodesPost",
		strings.ToUpper("Post"),
		"/code/selectCodes",
		CodeSelectCodesPost,
	},

	Route{
		"CustomersSelectCustomerPost",
		strings.ToUpper("Post"),
		"/customers/selectCustomer",
		CustomersSelectCustomerPost,
	},

	Route{
		"ItemClassSelectItemsClassPost",
		strings.ToUpper("Post"),
		"/itemClass/selectItemsClass",
		ItemClassSelectItemsClassPost,
	},

	Route{
		"NoticesSelectNoticesPost",
		strings.ToUpper("Post"),
		"/notices/selectNotices",
		NoticesSelectNoticesPost,
	},

	Route{
		"BranchesSaveBrancheCustomersPost",
		strings.ToUpper("Post"),
		"/branches/saveBrancheCustomers",
		BranchesSaveBrancheCustomersPost,
	},

	Route{
		"BranchesSaveBrancheInsurancesPost",
		strings.ToUpper("Post"),
		"/branches/saveBrancheInsurances",
		BranchesSaveBrancheInsurancesPost,
	},

	Route{
		"BranchesSaveBrancheUsersPost",
		strings.ToUpper("Post"),
		"/branches/saveBrancheUsers",
		BranchesSaveBrancheUsersPost,
	},

	Route{
		"ImportsSelectImportItemsPost",
		strings.ToUpper("Post"),
		"/imports/selectImportItems",
		ImportsSelectImportItemsPost,
	},

	Route{
		"ImportsUpdateImportItemsPost",
		strings.ToUpper("Post"),
		"/imports/updateImportItems",
		ImportsUpdateImportItemsPost,
	},

	Route{
		"InitializerSelectInitInfoPost",
		strings.ToUpper("Post"),
		"/initializer/selectInitInfo",
		InitializerSelectInitInfoPost,
	},

	Route{
		"ItemsSaveItemCompositionPost",
		strings.ToUpper("Post"),
		"/items/saveItemComposition",
		ItemsSaveItemCompositionPost,
	},

	Route{
		"ItemsSaveItemsPost",
		strings.ToUpper("Post"),
		"/items/saveItems",
		ItemsSaveItemsPost,
	},

	Route{
		"ItemsSelectItemsPost",
		strings.ToUpper("Post"),
		"/items/selectItems",
		ItemsSelectItemsPost,
	},

	Route{
		"TrnsPurchaseSavePurchasesPost",
		strings.ToUpper("Post"),
		"/trnsPurchase/savePurchases",
		TrnsPurchaseSavePurchasesPost,
	},

	Route{
		"TrnsPurchaseSelectTrnsPurchaseSalesPost",
		strings.ToUpper("Post"),
		"/trnsPurchase/selectTrnsPurchaseSales",
		TrnsPurchaseSelectTrnsPurchaseSalesPost,
	},

	Route{
		"TrnsSalesSaveSalesPost",
		strings.ToUpper("Post"),
		"/trnsSales/saveSales",
		TrnsSalesSaveSalesPost,
	},

	Route{
		"StockMasterSaveStockMasterPost",
		strings.ToUpper("Post"),
		"/stockMaster/saveStockMaster",
		StockMasterSaveStockMasterPost,
	},

	Route{
		"StockSaveStockItemsPost",
		strings.ToUpper("Post"),
		"/stock/saveStockItems",
		StockSaveStockItemsPost,
	},

	Route{
		"StockSelectStockItemsPost",
		strings.ToUpper("Post"),
		"/stock/selectStockItems",
		StockSelectStockItemsPost,
	},
}
